# Generated by Django 5.1.3 on 2024-11-20 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_hotel_alter_review_place_review_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='booking_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
